import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/providers";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";
import AuthProvider from "../api/auth/[...nextauth]/auth-provider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// })

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",

  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    url: "https://greengodelivery.ge",
    siteName: "GreenGo Delivery",
    images: [
      {
        url: "https://greengodelivery.ge/og-image.png",
        width: 1200,
        height: 630,
        alt: "GreenGo Delivery",
      },
    ],
    locale: "en_US",
    type: "website",
  },
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  const session = (await getServerSession(authOptions)) as undefined;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className={` antialiased invisible-scrollbar`}>
        <AuthProvider session={session}>
          <Providers locale={locale}>
            {children}
            <Toaster />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
